### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by promuks** [quantumui/quantumui#12]
I generated an angular-full-stack app using yeoman.I updated the bower.json to add  
   "moment": ">=2.9.0",
    "quantumui": "latest"
and ran bower install.
I updated app.js to include ngAnimate and ngQuantum
angular.module('yeomanTryApp', [
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'ngRoute',
  'ui.bootstrap',
  'ngAnimate',
  'ngQuantum'
])
My index.html has css and js like below
 <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <base href="/">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    
    
      
      <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css" />
      <link rel="stylesheet" href="bower_components/quantumui/dist/css/quantumui.css" />
      
    
    
    <link rel="stylesheet" href="app/app.css">
      
      <link rel="stylesheet" href="app/app.css">
      <link rel="stylesheet" href="app/main/main.css">
      <link rel="stylesheet" href="components/modal/modal.css">
      
    
  </head>

```
  <script src="bower_components/jquery/dist/jquery.js"></script>
  <script src="bower_components/angular/angular.js"></script>
  <script src="bower_components/angular-resource/angular-resource.js"></script>
  <script src="bower_components/angular-cookies/angular-cookies.js"></script>
  <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
  <script src="bower_components/angular-route/angular-route.js"></script>
  <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
  <script src="bower_components/lodash/dist/lodash.compat.js"></script>
  <script src="bower_components/moment/moment.js"></script>
  <script src="bower_components/angular-animate/angular-animate.js"></script>
  <script src="bower_components/quantumui/dist/js/quantumui.js"></script>
```

I went to the main.html page and added 
 <input type="checkbox" ng-model="switchModel" data-nq-switch-button="">
and i see the check box but dont see the styles or the animation and I see the following error in the console.

TypeError: undefined is not a function
    at Object.fn.unBindTriggers (quantumui.js:392)
    at Object.angular.module.provider.directive.angular.module.provider.$get.$master.init (quantumui.js:4235)
    at quantumui.js:4277
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$get.Scope.$eval (angular.js:14466)
    at Scope.$get.Scope.$digest (angular.js:14282)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)angular.js:11655 (anonymous function)angular.js:8596 $getangular.js:13256 processQueueangular.js:13264 (anonymous function)angular.js:14466 $get.Scope.$evalangular.js:14282 $get.Scope.$digestangular.js:14571 $get.Scope.$applyangular.js:9698 doneangular.js:9888 completeRequestangular.js:9829 requestLoaded

What am I doing wrong?

**Comment by mehmetotkun** [comment]
OK @promuks This means there is a conflict between @quantumui and ui-bootstrap. Actually, there is no reason to use both with each other. Beacuse @quantumui has more modules than **ui-bootstrap**. However if you want to use both with each other, you must changes service names which cause to conflict. For example. Both @quantumui and angular-strapt has `$modal` service. You must change ui-bootstrap modal service as `$modalStrap` in source code or you can remove ui-bootstrap from your project.

First, try remove to check if problem solve. Then make your decision.

**Comment by mehmetotkun** [comment]
Also you can check this issue

https://github.com/quantumui/quantumui/issues/1

**Comment by promuks** [comment]
Hi, Thanks for your prompt reply.
I removed the bootstrap ui and that error goes away, but the animation or
styles I still cannot see.
Thanks,

On Thu, Mar 19, 2015 at 12:32 PM, mehmetotkun notifications@github.com
wrote:

> Also you can check this issue
> 
> #1 https://github.com/quantumui/quantumui/issues/1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/quantumui/quantumui/issues/12#issuecomment-83652455.

## 

Thanks,
Mukul Nadkarni,

http://www.linkedin.com/in/mukul37

**Comment by mehmetotkun** [comment]
Apparently, `effect-light.min.css` doesn't exist in your page. You should check it. Also If you mean skin in demos with **styles** quantumui don't include a customized bootstrap skin. Because most of developers don't like customized skins. You should create your custom skin by editing LESS source. Changing on bootstrap LESS would automatically effect quantumui LESS.

Also for icons of components, you should customize this configuration file and add it to your page. https://github.com/quantumui/quantumui/blob/master/config/icons.js
