### ISSUE TITLE
Keyboard navigation support

### ISSUE THREAD

**Issue by kevkha** [quantumui/quantumui#13]
I'm impressed with your works. Can you direct me to or show how to create an UI that supports keyboard navigations like in native Bootstrap? Ideally, some basic navigations around navbar, menu, search, table, listvew ect.. Thanks in advance.

**Comment by mehmetotkun** [comment]
You should specify your case, there are tons of keyboard navigation usage options in an application.

**Comment by kevkha** [comment]
Thanks for your response. Let me try with this diagram.
1. Once the page is loaded the focus is set on first NAV button inside Purple div, the user should be able to navigate between NAV's with Left and Right arrows. Enter key event to select (given that no further drop down, creating complications).
2. From Purple user should be able to move down to Yellow and first land on Search box for instance (focus is set on this). User inputs search term and press Enter key.
3. User then Down arrow to search results and up again as desired. Enter event on each item is ready.
4. User should able to go Up to Purple or down to Cyan and Up again as desired.

![image](https://cloud.githubusercontent.com/assets/1807308/7077261/e641a76e-ded4-11e4-9f80-a1f4b849a84b.png)

**Comment by mehmetotkun** [comment]
OK. This isn't an issue of #QuantumUI. If you want to use keyboard there are two common way make an application managable with keyboard. 

First one is (Accessible Rich Internet Applications (WAI-ARIA))[http://www.w3.org/TR/wai-aria/] 

The second one is using javascript `keydown` event.

All components of #QuantumUI support keyboard events based on their requirements. 

You can develop your custom solution by combination **WAI-ARIA** and javascript. Also, there are lots of documentation and plugins on internet.

Post this issue via stackoverflow and i think you will find more help from there.
