### ISSUE TITLE
Is the getting started site down?

### ISSUE THREAD

**Issue by dmitriz** [quantumui/quantumui#15]
All down:
http://quantumui.org/
http://quantumui.org/ui/
http://quantumui.org/ui/start/

**Comment by mehmetotkun** [comment]
Yes I have been trying to change hosting provider. Unfortunately, arvixe
suspend my hosting plan due to 10$ :(. I was very angry and changin hosting
provider. It may take some hours.

2015-04-15 9:27 GMT+03:00 Dmitri Zaitsev notifications@github.com:

> All down:
> 
> http://quantumui.org/http://quantumui.org/ui/http://quantumui.org/ui/start/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/quantumui/quantumui/issues/15.

## 

_Mehmet Ötkün_

**Comment by dmitriz** [comment]
Have you tried Github hosting?
No reason to pay for hosting open source projects!

**Comment by mehmetotkun** [comment]
I know, In start I plan the project as commerical, for this reason there
are some c# backend settings for documentation management. After I
transform backend to node, I will host it on github.

2015-04-15 9:41 GMT+03:00 Dmitri Zaitsev notifications@github.com:

> Have you tried Github hosting?
> No reason to pay for hosting open source projects!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/quantumui/quantumui/issues/15#issuecomment-93219899.

## 

_Mehmet Ötkün_

**Comment by dmitriz** [comment]
I imagine you want a clear separation between your open source and commercial parts, so having two separate repos sounds like a good choice. 

Documentation is normally generated locally and uploaded as web app. And if you need any database support - try Parse.com!

**Comment by mehmetotkun** [comment]
Actually, I have been preparing a commerical repos which include more components, themes and different configurations. Currently I have some priority issues from transforming documentation app to a github page.

Also there are no more jobs in backend. I just manage routing fallback and call for some ajax demo requests. Currently don't need any database, just some json files I have.
