### ISSUE TITLE
Select and ng-model

### ISSUE THREAD

**Issue by hougoul** [quantumui/quantumui#18]
Hi,
I've got an issue with ng-model and quantum select.
the following doesn't work has expected:
![image](https://cloud.githubusercontent.com/assets/12064482/7279646/afb72edc-e91d-11e4-84e5-d5048075fc23.png)

When I select an item input is enabled like expected but when I remove the selected element the input stay enable.
Do you have any idea?

Thanks

**Comment by mehmetotkun** [comment]
`nq-select` directive has own `$scope`, If you define a model for a directive has own scope you should define its model in any parent for accesing in it.

For this reason define `Todo.name` property with `ng-init` on a parent of `nq-select`.

Something like below

```
<div ng-init="Todo.name=null">
   <ul nq-select=""  ng-model="Todo.name"></ul>
 <input ng-model="Tata" ng-disabled="Todo.name===null">
</div>
```

**Comment by hougoul** [comment]
Hi,
I do this change in quantumui-nojq.js:
line 6963 (function renderItem(item, key) )
I change controller.$modelValue = null by  controller.$setViewValue(null); 
and now everything works fine (before that my model didn't change).

**Comment by mehmetotkun** [comment]
Actually, the proper solution is `ng-disabled="!Todo.name"` means disable this when **Todo.name** is null or undefined. I advice remove your change and use a proper solution. Beacuse, your chance may cause another problem. $setViewValue(null) may force additional diggest cycle.
