### ISSUE TITLE
$modal sample request

### ISSUE THREAD

**Issue by hougoul** [quantumui/quantumui#19]
Hi,
Is it possible to have a sample with an angular template (like for angularjs.bootstrap.ui $modal)
for example
![image](https://cloud.githubusercontent.com/assets/12064482/7279630/9281557c-e91d-11e4-97da-1ff709acab9e.png)

Thanks for your help
Best regards

**Comment by mehmetotkun** [comment]
Yess of course. You can set any template by `qo-template` option. Also, `qo-content-template` is another template obtion for only templating modal template. 

$scope arguments are listed http://quantumui.org/appdoc/documents/quantumui/modal/ under SCOPE ARGUMENTS title.

My suggestion is using `qo-content-template`. You can costomizing header and footer with `.custom-header` and `custom-footer` classes. Thus, `animateTarget` and other modal shell will stay as default.

Here is **contentTemplate** examples of demo; http://quantumui.org//templates/modalcontent.html look at the source code please.
