### ISSUE TITLE
button (icon) of the select is not displayed

### ISSUE THREAD

**Issue by mastermind1981** [quantumui/quantumui#2]
Hi,

The icon of the select (on the atmost right of the button) is not displayed i got a small square in his place.

Thanks

**Comment by mehmetotkun** [comment]
This is a css isue, I have been tried to add multiple option for icon. Thanks for feedback...

**Comment by ghost101** [comment]
Datepicker does not display any icons - though functionality is fine. Assume it might be also css issue - but I have used example code directly as stated in documentation.

**Comment by mehmetotkun** [comment]
Ohh sorry!
I have forgotten my custom icon package as default for all components. You can change them by using configurations.

Ex: for datepicker for default bootsrap glyphicon 

```
myApp.config(['$datepickerProvider',function($datepickerProvider) {
          var mydefaults = {
           nextIcon:'glyphicon glyphicon-chevron-right',
            prevIcon:'glyphicon glyphicon-chevron-left',
            timeIcon:'glyphicon glyphicon-time',
            closeIcon: 'glyphicon glyphicon-remove',
            downIcon: 'glyphicon glyphicon-chevron-down',
            upIcon: 'glyphicon glyphicon-chevron-up',
            ...
        }
        angular.extend($datepickerProvider.defaults, mydefaults)
    }]);
```

Maybe you would prefer Fontawesome icons or naything else.

For all list of configuration options please look at [this documentation page](http://angularui.net/appdoc/documents/quantumui/datepicker/) 

Also they can be setted as attribute.

**Comment by ghost101** [comment]
JZK  - Thank You - Perfect!

**Comment by zymplsi** [comment]
I thought it was a conflict with my bootstrap css which I couldn't resolve such that I ditched the quantum ui datepicker and tried to look elsewhere. Now it works fine, but shouldn't this work out of the box? Also
It looks like there is another icon property 'todayIcon' which is not documented. Anyway, great work!

**Comment by mehmetotkun** [comment]
Thannks for notice, We have forgotten to document **todayIcon**, I would add them to option. Also we would change default ICON options to Bootstrap default. 

We have tried to icon options as virtual as we can. Because all developer may have different icon preferance. Maybe Fontawesome, Ionicons or custom Icomoon package. In this case, you should add a piece of configuration code to your **app** config.

This is all list of icon in components configured for Bootstrap.css default icon. You load as seperate js file or paste to your config file.

```
angular.module('ngQuantum').config(
    ['$datepickerProvider',
     '$loadingButtonProvider',
     '$colorPickerProvider',
     '$loadingProvider',
     '$modalProvider',
     '$selectProvider',
      function ($datepickerProvider, $loadingButtonProvider, $colorPickerProvider, $loadingProvider, $modalProvider, $selectProvider) {
          var dpdef = $datepickerProvider.defaults,
              lbdef = $loadingButtonProvider.defaults,
              cpdef = $colorPickerProvider.defaults,
              ldef = $loadingProvider.defaults,
              mdef = $modalProvider.defaults,
              sdef = $selectProvider.defaults
          //datepicker icons
          dpdef.todayIcon = 'glyphicon glyphicon-refresh';
          dpdef.nextIcon = 'glyphicon glyphicon-chevron-right';
          dpdef.prevIcon = 'glyphicon glyphicon-chevron-left';
          dpdef.timeIcon = 'glyphicon glyphicon-time';
          dpdef.closeIcon =  'glyphicon glyphicon-remove';
          dpdef.downIcon =  'glyphicon glyphicon-chevron-down';
          dpdef.upIcon = 'glyphicon glyphicon-chevron-up';

          //loadingButton icons
          lbdef.spinner = '<i class="glyphicon glyphicon-repeat spin"></i> '; //any html accepted
          lbdef.successIcon = '<i class="glyphicon fu-check  flash"></i>'; //any html accepted
          lbdef.errorIcon = '<i class="glyphicon glyphicon-ok flash red"></i> '; //any html accepted
          lbdef.timeoutIcon = '<i class="glyphicon glyphicon-bell"></i> '; //any html accepted

          //colorpicker icons
          cpdef.iconDown = 'glyphicon glyphicon-menu-down';
          cpdef.iconUp = 'glyphicon glyphicon-menu-up';

          //loading service icons
          ldef.spinnerIcon = '<i class="glyphicon glyphicon-repeat spin-icon spin"></i>'; //any html accepted

          //modal icons
          mdef.closeIcon = '<i class="glyphicon glyphicon-remove"></i>'; //any html accepted

          //select icons
          sdef.clearIcon = '<i class="glyphicon glyphicon-remove"></i>'; //any html accepted
          sdef.spinner = '<i class="glyphicon glyphicon-repeat spin"></i>'; //any html accepted

    }])
```
