### ISSUE TITLE
modal under the backdrop 

### ISSUE THREAD

**Issue by pibi** [quantumui/quantumui#20]
from actual master, a simple modal is misplaced under the backdrop.
take a look at the screenshot
![image](https://cloud.githubusercontent.com/assets/191260/7302771/fd10181e-e9eb-11e4-8829-76e56a55dcf7.png)

**Comment by mehmetotkun** [comment]
Please check your backdrop `z-index` propery, You can remove `z-index` for backdrop or it must be smaller than `.modal-dialog`

**Comment by pibi** [comment]
Thanks for the prompt reply and the great project. 
The screenshot comes from a very trivial implementation with the actual master, take a look at this [gist](https://gist.github.com/pibi/42acfbb88f60f65043d9). 

I've missed something?
thanks

**Comment by mehmetotkun** [comment]
I will fixed this issue for next release. Currently you can add below style at the end of your page head.

```
<style type="text/css">
.modal-backdrop {
     z-index:0;
}
</style>
```

**Comment by mehmetotkun** [comment]
solved

**Comment by pibi** [comment]
confirmed, thanks!
