### ISSUE TITLE
vertical slider doesn't work on modals

### ISSUE THREAD

**Issue by pibi** [quantumui/quantumui#21]
a vertical slider doesn't work when placed inside a modal

![image](https://cloud.githubusercontent.com/assets/191260/7302790/1fd0a198-e9ec-11e4-9c32-df3f63d48215.png)

**Comment by mehmetotkun** [comment]
There might be a `float` problem in parent of slider element in your modal content.  If you add 'float' property to an element, it's parent must have '.clearfix' class.

**Comment by pibi** [comment]
As stated in #20,  [this](https://gist.github.com/pibi/42acfbb88f60f65043d9) is a very simple implementation to show you the bugs we have found on our web application.
Please let me know if I have missed something.
thanks

**Comment by mehmetotkun** [comment]
OK! Thank you for your specific issue. There is an compiling issue when using content template. I will upload a new release after this weekend which include some bug-fixes and new features.

Currently you can solve your case like below.

This is your modal toggle button

```
 <button type="button" data-nq-toggle-modal="#sliderInModal" class="btn btn-default">
     Slider In Modal
  </button>
```

And this is your modal content include slider

```
<div id="sliderInModal" class="clearfix" data-nq-modal="" data-qo-independent="true" data-qs-title="Slider In Modal">
       <div class="col-lg-3" ng-init="rangeSliderVer = 5">
            <input type="range" data-ng-model="rangeSliderVer" data-nq-slider="" data-direction="vertical" size="120">
        </div>
</div>
```

**Comment by pibi** [comment]
Ok, thanks! Please, let me know when you release a fix, so I will test it.
thanks again

**Comment by mehmetotkun** [comment]
It is probably after this weekend. If you follow me on twitter, facebook, or google+ you may see my anouncement.

**Comment by pibi** [comment]
Great, I tested your workaround and it works, also with ng-include:

``` html
<button type="button" data-nq-toggle-modal="#sliderInModal" class="btn btn-default">
     Slider In Modal
  </button>
```

and

``` html
<div id="sliderInModal" class="clearfix" data-nq-modal="" data-qo-independent="true" data-qs-title="Slider In Modal">
   <div ng-include="'simple.html'"></div>
</div>
```

thanks again.

**Comment by mehmetotkun** [comment]
solved
