### ISSUE TITLE
nqTooltip on Input

### ISSUE THREAD

**Issue by hougoul** [quantumui/quantumui#22]
Hi,
I've just see that when I add nq-tooltip qs-title="Something" on input, I cannot click on this input.

Do you have any idea to fix it?

Best regards

**Comment by mehmetotkun** [comment]
Currently ,you can fix it by below code. In next releases I will try to solve properly.

```
app.directive('nqTooltip',
      function () {
          return {
              restrict: 'EAC',
              link: function postLink(scope, element, attr) {
                  if(element[0].tagName.toLowerCase() == 'input')
                      element.on('click', function () {
                          element.focus();
                      })
              }
          };
      })
```

**Comment by hougoul** [comment]
Thanks

**Comment by hougoul** [comment]
Hi,
Another problem,
On input you cannot select a part of the text when you use nqTooltip.
best regards

**Comment by hougoul** [comment]
Hi,
I had a bug on tooltip doesn't hide in some case and fixed it with 
in .provider('$popMaster'
... $master.leave = function (evt)
I add this

```
                      if (!exrtadelay) {
                          return $master.hide();
                      }
```

best regards

**Comment by mehmetotkun** [comment]
solved
