### ISSUE TITLE
nqDatepiker Time mode

### ISSUE THREAD

**Issue by hougoul** [quantumui/quantumui#23]
Hi,
Just a question when Datepiker is on time mode How I can select the actual time without changing it?

Thanks
best regards

**Comment by mehmetotkun** [comment]
Do you mean time now?

**Comment by hougoul** [comment]
Yes

**Comment by mehmetotkun** [comment]
Currently today button is just visible on datetime mode. 

However you can add small button to your input for setting now. 

Try something below

**HTML**

```
<div class="input-group">
    <input type="text" ng-model="inputTime" nq-datepicker="" qo-mode="time" class="form-control"/>
   <span class="input-group-addon" ng-click="setTimeToNow('inputTime')"><i class="glyphicon glyphicon-time"></i></span>
</div>
```

Controller Function

```
$scope.setTimeToNow = function(model) {
   $scope[model] = new Date();
}
```

I didn't test above code, If not work, you can try in $scope.$apply function like below.

```
$scope.setTimeToNow = function(model) {
    $scope.$apply(function(){
         $scope[model] = new Date();
    }) 
}
```

**Comment by hougoul** [comment]
Thanks
