### ISSUE TITLE
ngDatetimepicker

### ISSUE THREAD

**Issue by hougoul** [quantumui/quantumui#24]
Hi,
when I have this configuration
![image](https://cloud.githubusercontent.com/assets/12064482/7348153/50f16a7c-ecef-11e4-9e77-bbef4988e7be.png)

I have two problems (but linked together):
1 - everytime I click on a date the focus move to the next date picker:
![image](https://cloud.githubusercontent.com/assets/12064482/7348197/ce88f6b2-ecef-11e4-8b37-7618111e632f.png)

2 - I can have the following too:
![image](https://cloud.githubusercontent.com/assets/12064482/7348224/fcd684bc-ecef-11e4-8fbd-ebde2783b6cd.png)

Best regards

**Comment by hougoul** [comment]
I think it's due to range. all date are linked together.
But I cannot reproduce the default date range behavior.
(nq-datepicker qo-min-date-from="#previousID" qo-default-range="0" qo-min-range="0")
and by default all are allowWrite = true;

**Comment by mehmetotkun** [comment]
Min range cannot be smaller that **1**. You should set `rangeType` option `hours` or `minutes`. It may works.
