### ISSUE TITLE
nqSelect with complex object

### ISSUE THREAD

**Issue by hougoul** [quantumui/quantumui#25]
Hi,
I have the following:
<button class="btn btn-xs" ng-model="Object"
                               ng-change="Selected(Object)"
                                nq-select
                                qo-result-key="ObjectList"
                                ng-options="obj as obj .Description for obj in ObjectList"
                                qo-disable-clear="true"
                                qo-filterable="false"></button>

<p>{{Object.Comments}}</p>

with ObjectList = [{Code:"1", Description:"Test 1", Comments:"Comments1"},{Code:"2", Description:"Test 2", Comments:"Comments2"},{Code:"3", Description:"Test 3", Comments:"Comments3"}];

it works fine when I select, change .... but the first time I load and Object is initialize with one of the value ( for example ObjectList[1]) the drop down don't show the Object.Description 

Is it a easy way to fix it?
I need it because I have 3 dropdown linked together.

Thanks

**Comment by mehmetotkun** [comment]
Instead of using ng-option you can use custom render option.

Please look at examples here  http://quantumui.org/appdoc/documents/quantumui/select/custom
