### ISSUE TITLE
nqTagsInput: Empty dropdown list  when inserting a tag that was previously removed

### ISSUE THREAD

**Issue by pibi** [quantumui/quantumui#27]
If I input a value into a nqTagsInput and then I remove it, I can't select it again from the dropdown list.
Tested with this code:

``` html
  </head>

  <body ng-cloak ng-controller="SimpleController">

      <label></label>
      <input type="text" id="highlightFriends" ng-model="friends" data-nq-tags-input="friendlist" data-qo-placeholder="insert friends..."   data-qo-multiple="true" >

  </body>

  <script>
  var app = angular.module('vtrack', [
    'ngSanitize',
    'ngAnimate',
    'ngQuantum'
  ])
  .controller('SimpleController', ['$rootScope','$scope', function ($scope) {

    $scope.log=function(){
      console.log.apply(console,arguments)
    }

    $scope.friendlist=['marco','ciccio','cristina']

  }])
  </script>
</html>
```

**Comment by mehmetotkun** [comment]
Sorry @pibi , I didn't understand your case clearly.

What is your complate scenario.
1. select **marco** form dropdown
2. remove **marco**
3. can't select marco again...

is it true?

**Comment by pibi** [comment]
quite right:
1. input **ma**
2. select **marco** form dropdown
3. remove **marco**
4. input **ma** again
5. **marco** is not showed, so I can't select it again

**Comment by mehmetotkun** [comment]
Yes thank you for your notice.

It occurs just for item removed first time. I will analyze for reason.
Namely,

6- input **ci**
7- select **ciccio**
8- remove **ciccio**
9- input **ci** again
10- **ciccio** is shown

also **macro** is available on options but connot shown when filter.
...

**Comment by mehmetotkun** [comment]
solved

**Comment by pibi** [comment]
confirmed, thanks!
