### ISSUE TITLE
Unable to show popover properly 

### ISSUE THREAD

**Issue by aoutfast** [quantumui/quantumui#29]
Hello, first i have to say Quantum UI is really a game changer in building UI with angular js thanks guys for that.
I am only having a issue with the popover after i implemented it when i click the popover shows up but no style no animation. PS : i removed bootstrap UI for the conflit issue. 
this is the logged error :
"Uncaught TypeError: Cannot read property 'then' of undefined"  at  quantumui.min.js:7

**Comment by mehmetotkun** [comment]
Thanks for the compliments. Can you share your code?
