### ISSUE TITLE
Not possible to set state of checkbox

### ISSUE THREAD

**Issue by Georgi87** [quantumui/quantumui#30]
Adding/removing the attribute "checked" has no effect on the state of the checkbox? Is it possible to reset a checkbox?

**Comment by mehmetotkun** [comment]
Why not set `ng-model` property true or false? "checked" attribute don't watched by defaulty in angular.js. Please look at https://docs.angularjs.org/api/ng/input/input%5Bcheckbox%5D page for checkbox.

**Comment by Georgi87** [comment]
Changing the ng-model property does not change the state of the checkbox in my interface.

```
<input type="checkbox" ng-model="buy_order.create_open_order" data-label-text="Create order" data-true-label="Yes" data-false-label="No" data-nq-switch-button="" data-theme="primary">
```

Setting buy_order.create_open_order to true or false, doesnt change the checkbox.

**Comment by mehmetotkun** [comment]
OK, As I see, there var a scope problem.
Currently you can solve by initializing `ng-model` before or parent element.
Something like this. 

```
<div class="ng-model" ng-init="buy_order.create_open_order = buy_order.create_open_order || false">
<input type="checkbox" ng-model="buy_order.create_open_order" data-label-text="Create order" data-true-label="Yes" data-false-label="No" data-nq-switch-button="" data-theme="primary">
</div>
```

Bu this way you ng-model propery would be available in parent scope.

**Comment by Georgi87** [comment]
Unfortunately this has no effect for me neither. No matter if I do 

```
ng-init="buy_order.create_open_order = false"
or
ng-init="buy_order.create_open_order = true"
```

The checkbox is always not checked.

**Comment by mehmetotkun** [comment]
Ok. Sorry, Now I find to reason.

If you can edit the code, search for  `nqSwitchButton` directive, 

then find `scope.$watch(attr.ngModel` 

then replace it with `scope.$parent.$watch(attr.ngModel`

no other thing required to do.

**Comment by Georgi87** [comment]
Cool, thanks, it works now with the parent div. However I still cannot set the checkbox state in the angular controller. As changing the scope variable $scope.buy_order.create_open_order doen't have any effect on the state.

**Comment by mehmetotkun** [comment]
How do you change `$scope.buy_order.create_open_order`

if state is a dom event you shoul change it in 

```
$scope.$apply(function(){
    $scope.buy_order.create_open_order=...
})
```

**Comment by Georgi87** [comment]
thank you. all works now with your proposed solution!
