### ISSUE TITLE
Standalone Pageable components from Demo page.

### ISSUE THREAD

**Issue by rasekar2000** [quantumui/quantumui#31]
Hello @mehmetotkun 
In Continuation to #28 , we are trying to bring your Pageable component alone into our existing bootstrap angular framework ..

 So, first trying to make this pageable component , especially the demo code alone , work independent of any other frills. But i am unsuccessful .

 [Google Drive View Access for code extraction](https://drive.google.com/folderview?id=0B1jv0flp8lv9flNRMWpPREh2aVJLX3NNOUN5T3ZPNkJNbXlCMjdreGw5VzVOckk2d3BkTHM&usp=sharing)

Issue in a screen: 
https://docs.google.com/file/d/0B1jv0flp8lv9ZXJTWWhUMU5LV0E

 If you have sometime, can you please suggest a solution ..

 This may be the use case for already up and running sites, who just need few components instead of the entire suite. 

Thanks and Regards,
Raj

**Comment by mehmetotkun** [comment]
Hi Raj,

As I said before, Pageable is not ready to share yet. I hope, I can share it until next week. It has more features then current demo.

**Comment by rasekar2000** [comment]
Hi @mehmetotkun , Yes i understand.. Just to ensue that the requirement of Pageable can be included with the following 
   a) Easy to plug Pluggable component with other Angular BootStrap UI Framework as well . :-)
   b) Responsive enough for the Pageable Datatable as well.
         Reference :   http://www.primefaces.org/showcase/ui/data/datatable/group.xhtml

Thanks and Regards,
Raj

**Comment by rasekar2000** [comment]
Cool.. Primefaces JSF with jQuery as UI , is getting much more Responsive in nature for most of the Components.. 

https://twitter.com/primefaces

**Comment by rasekar2000** [comment]
Hello @mehmetotkun , 

 Is there any timeline to deploy the Pageable component in Github.

Thanks and Regards,
Raj

**Comment by mehmetotkun** [comment]
Yes Raj,

At 10.06.2015 all updates and pageable will be published.

Thanks,

**Comment by rasekar2000** [comment]
Thank you.

**Comment by rasekar2000** [comment]
Hello Team,

```
   Is 10.06.2015 mean June 10th or October 6th?
```

Thanks and Regards,
Raj

**Comment by rasekar2000** [comment]
Any update @mehmetotkun  atleast on the old source code , pls?

Thanks and Regards,
Raj
