### ISSUE TITLE
nqTagsInput: support for custom "enter" key

### ISSUE THREAD

**Issue by pibi** [quantumui/quantumui#32]
Can you add support for custom key code to "create" a new tag?
I'm looking to use nqTagsInput on a email input field for a webmail, but
actually the code ([here](https://github.com/quantumui/quantumui/blob/master/src/components/select.js#L720)) supports only the "Enter" key code. It would be more user friendly if I can support also comma and semicolon.

**Comment by mehmetotkun** [comment]
I think you are looking for somthing like [ngList](https://docs.angularjs.org/api/ng/directive/ngList) directive. `nqTagsInput` is for styled option rendering and seperating options by comma is not a good idea.

**Comment by pibi** [comment]
I agree with you that nqTagsInput is for styled option rendering. Let me reword my needs: I use like the gmail new messages address field, where emails become tag like buttons. Gmail supports addresses input with the Enter key, but also with space, comma and semicolon. I think it could be more user friendly to support also these keycode, maybe with a specific option. So the options will not be separated by comma, but they will be pushed into the scope variable with these keycodes, exactly the same way it works actually with the Enter keycode.

**Comment by mehmetotkun** [comment]
OK. I see! However I am not sure to add this as a future to `nqTagsInput`.

I didn't tested but I think you can solve by adding a helper directive to input like below

```
app.directive('tagsInputExtend', function(){
   return {
     restrict: 'AC',
    link:function(scope, element, attr, controller){
        //find search input
       var searchInput = element.parent().find('.select-render-nav .select-input');
            searchInput.on('keypress', function(e){
            //you may need prevent this event not sure!
            //e.preventDefault();
            //e.stopPropagation();

            //validate keykodes you want
             if(/186|188/.test(e.keyCode)){
               //create enter event to run component function
               enterEvt =  document.createEvent('keypress');
               enterEvt.which = enterEvt.keyCode =13;
               element.trigger(enterEvt)
              }
            })
    },
   }
})
```

Then add this directive to your tagsInput element.

Hope it helps.
