### ISSUE TITLE
nqDatePicker does not close when selecting same date

### ISSUE THREAD

**Issue by PW999** [quantumui/quantumui#34]
Small test case to explain the problem:

| Action | Expectation | Result |
| --- | --- | --- |
| Click on the datePicker input field | pop-up should appear | ok |
| Click on an arbitrary date | pop-up closes and input field is filled in | ok |
| Clear the input field |  |  |
| Click on the input field | pop-up should appear | ok |
| Click on the same date as in step 2 | pop-up closes and input field is filled in | **nok: nothing happens** |

This happens when manually cleaning the input field or programatically.

**Comment by mehmetotkun** [comment]
solved
