### ISSUE TITLE
Dropdown closing and opening programmatically 

### ISSUE THREAD

**Issue by Sajan129** [quantumui/quantumui#35]
Hi, I m trying to implement quantum UI components in a new project. I m having troubles closing and opening dropdown.When user presses 'Yes' or 'No' , the dropdown must be closed from within respective function it calls.

I think $hide or $show can be used as mentioned in documents, but due to lack of example, I m not being able to use them as required. Could you help me out?

<a ng-if="!innerchilds.$edit" data-nq-dropdown="" data-qo-show-arrow="true" class="btn btn-danger btn-xs glyphicon glyphicon-remove" ></a>

```
                        <div class="dropdown-menu deleteConfirm" tabindex="-1" role="menu">
                            <div class="dc-header"><b>Are you sure?</b></div>
                            <div class="dc-body btn-group" role="group" >
                              <button type="button" class="btn btn-info" ng-click="deleteChildRecord()">Yes</button>
                              <button type="button" class="btn btn-danger" ng-click="cancelDeleteChildRecord()">No</button>
                            </div>

                        </div>
```

?

**Comment by mehmetotkun** [comment]
Sorry for late answer,

You can get `$scope` of your menu like below

```
var ddScope = angular.element('#myDropdown').scope();
//use show or hide
ddScope.$show() or ddScope.$hide()
```
