### ISSUE TITLE
quantumui demo page's offcanvas menu not working (i.e scrolling) in mobile browser (chrome)

### ISSUE THREAD

**Issue by lapak10** [quantumui/quantumui#36]
i recently tried to view the demo of quantumui on my phone (Android) in chrome browser... but i was not able to scroll the offcanvas menu downwards... only the page is getting scrolled on mobile devices... i dont know about other browsers... but in chrome its working.

**Comment by whelaro** [comment]
I'm actually having problems with it in Desktop Chrome as well. I see the menu, I see the scroll bar, I can't drag it in any way to load all items. If I hover over it, it becomes dark and a bit larger, but doesn't take click/dragging input.

**Comment by mehmetotkun** [comment]
Hi dears,

I am sorry, I really didn't understand your cases. Is you problem about scrrollbar, aside or dropdown menu.. ? which one?

**Comment by lapak10** [comment]
Left sidebar ( Probably ASIDE) ... i guess the z-index is messing up things here... check this menu in mobile devices [chrome browser] and rest you will get to know.
![Image of sidebar](http://i62.tinypic.com/i4et1w.png)

**Comment by meishier** [comment]
if you are using jquery, this will happen.

change services mouse.js 's wheelHandler function

            function wheelHandler(element, orgEvent, callback) {
                var orgEvent = orgEvent || window.event,
                    args = [].slice.call(arguments, 1),
                    delta = 0,
                    deltaX = 0,
                    deltaY = 0,
                    absDelta = 0,
                    offsetX = 0,
                    offsetY = 0;
                orgEvent = orgEvent.originalEvent || orgEvent; //here is the fix

**Comment by mehmetotkun** [comment]
solved

**Comment by cutterbl** [comment]
Closed? I still can't scroll that menu, in Chrome or Safari on an iPad. I also cannot scroll the options in any of the Select examples, Search in a Select, or select any of the heavy format options in the Select examples.

**Comment by ghost** [comment]
The Quantum UI demo page is broken in several places out of the box.  The dropdown does not work, collapse, carousel and a few others as well.  I am confused.  I followed the bower install and the manual download and they all have the same issues.  I am running Windows 10 with Xampp.  Any help is appreciated.

Update:
Just reinstalled the master file and by toggling the aside all features seem to work.  Odd.

**Comment by djmarcus1** [comment]
Hello!

New message, please read http://master-mobile-techs.com/gone.php?cchu

djmarcus@m5inc.com
