### ISSUE TITLE
Overlay coming over the modal window

### ISSUE THREAD

**Issue by lapak10** [quantumui/quantumui#37]
The modal window is getting overshadowed due to overlay. [chrome_browser-desktop]

![Modal inside Overlay](http://i61.tinypic.com/261kghx.png)

PS: 1)I am not using UI.bootstrap.
2) Console showing ---Uncaught TypeError: a.then is not a function

**Comment by lapak10** [comment]
UPDATE:  Ok... its the problem with the z-index .... i tweaked to make it work for now... but i think there exists a much better way.
![screen shot 2015-06-18 at 3 47 17 am](https://cloud.githubusercontent.com/assets/525740/8220079/c8205f86-156c-11e5-9c7d-7234920023cc.png)
Tweak:-
//modal dialog window
.modal-dialog {
         //Adding just 1 higher value than the z-index of modal-backdrop which is 1040
          z-index: 1041;
}

**Comment by mehmetotkun** [comment]
solved
