### ISSUE TITLE
Datetime picker Icons not displaying

### ISSUE THREAD

**Issue by Georgi87** [quantumui/quantumui#38]
They work on the demo page:
http://quantumui.org/appdoc/documents/quantumui/datepicker/

But in the Git repo they don't work, it is blank. I found out that I had to copy the addon.css and their fonts to make them show up on my local page. Aren't they supposed to be included?

Thanks for you effort!

**Comment by meishier** [comment]
you need font fullAdmin-icon.woff also.

**Comment by mehmetotkun** [comment]
Please read this instruction carefuly, You can customize icons in [icons.js](https://github.com/quantumui/quantumui/blob/master/config/icons.js) file.

**Comment by Georgi87** [comment]
Thanks, got it!
