### ISSUE TITLE
Alert display problem

### ISSUE THREAD

**Issue by lapak10** [quantumui/quantumui#43]
I tried Alert but instead of getting growl like notifications....i am getting full width alert...like this

![Full with alert coming](http://i62.tinypic.com/lcua8.png)

**Comment by mehmetotkun** [comment]
you can do with css and custom placement option

First: set  `qo-placement="top-full"`

Then: set css like below

```
.alert-container.top-full{
    top:0; /*set value you want*/
   max-width:100%;  /*default is 300px;*/
   left:0;
   right:0;
}
```

`.alert-container` elements are prepended to  `body` and they have `fixed` position. You can change how you want.
