### ISSUE TITLE
'undefined' error when combining tabset/tab + controller + datepicker

### ISSUE THREAD

**Issue by djmarcus1** [quantumui/quantumui#46]
Hi

Below is a trivial example that generates an 'undefined' error on `currentDate` trying to reference `scope.currentDate.clone().toDate()` (line number 3070 in quantumui.js)

```
              ngModel.$render();
              apply(function () {
         -->         scope.modelDate = scope.currentDate.clone().toDate();
              })
```

The problem is reproducible on Chrome and FireFox.

(The full HTML is attached below)

The `<body>` of the HTML is:

```
<body ng-app="myApp">
<div nq-tabset="" data-effect="false">
    <div data-nq-tab="" data-heading="Tab #1" active="true">
        <div ng-controller="myCtrl">
            The date <br/>
            <input ng-model="myDate" data-nq-datepicker="" placeholder="Enter date" type="text" class="form-control"/>
        </div>
    </div>
</div>
```

</body>

What I discovered is that I can comment out the `tabset` and `tab` or comment out the `ng-controller` and the datepicker works. With _both_ in it fails (I'm attaching a screenshot from Chrome).

I tried to define a date (`$scope.myDate = moment()` in the controller and/or via `ng-init="myDate"`on the HTML) - but it made no difference.

-David

This is the entire HTML:

```
<!doctype html>
<html lang="en">

<head>
<meta charset="UTF-8">
<title>Quantum UI - Test</title>

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.css">
<link rel="stylesheet" href="file:///......../Scripts/QuantumUI/css/addon/effect-light.min.css">
<link rel="stylesheet" href="file:///......../Scripts/QuantumUI/css/quantumui.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.js"></script>

<script src="file:///......../Scripts/moment.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js"></script>
<script src="file:///......../Scripts/angular-sanitize.js"></script>
<script src="file:///......../Scripts/angular-animate.js"></script>
<script src="file:///......../Scripts/QuantumUI/js/quantumui.js"></script>

<script>
    'use strict';
    angular.module('myApp', ['ngSanitize', 'ngAnimate', 'ngQuantum'])
        .controller('myCtrl', ['$scope', function($scope) {  }
        ]);
</script>
</head>

<body ng-app="myApp">
<div nq-tabset="" data-effect="false">
    <div data-nq-tab="" data-heading="Tab #1" active="true">
        <div ng-controller="myCtrl">
            The date <br/>
            <input ng-model="myDate" data-nq-datepicker="" placeholder="Enter date" type="text" class="form-control"/>
        </div>
    </div>
</div>
</body>

</html>
```

**Comment by djmarcus1** [comment]
By the way, I updated the QUI source per your suggestion, but it does not fix this problem.

-David

I replaced the source lines, respectively with:

```
scope.minDate = angular.isString(options.minDate) ? moment(options.minDate, options.format) : angular.isDate(options.minDate) ? moment(options.minDate) : moment.isMoment(options.minDate) ? options.minDate.clone() : moment();

scope.maxDate = angular.isString(options.maxDate) ? moment(options.maxDate, options.format) : angular.isDate(options.maxDate) ? moment(options.maxDate) : moment.isMoment(options.maxDate) ? options.maxDate.clone() : moment();

scope.startDate = angular.isString(options.startDate) ? moment(options.startDate, options.format) : angular.isDate(options.startDate) ? moment(options.startDate) : moment.isMoment(options.startDate) ? options.startDate.clone() : moment();
```

**Comment by mehmetotkun** [comment]
OK. It seems that, the problem is more complicated than as we saw.

Currently; the component try detect `ng-model` value as formatted date string. However, developer may need to set model value as Date object event moment object. Hoever parsing javascript Date object on server may be difficult sometimes. For this reason using formatted string is better.

If this is the case, the component must detect the type of date, render input as formated string and don't change the type of model. I will looking for best practices and solve the problem in  the next release.

Currently you should use formatted date string for any options.

**Comment by djmarcus1** [comment]
In the sample program above, I specify NO date values what so ever. 

Any dates values/objects must therefore be internal to datepicker. The controller I defined is empty.

The datepicker is just:

```
<input ng-model="myDate" data-nq-datepicker="" placeholder="Enter date" type="text" class="form-control"/>
```

You should be able to reproduce the problem. There must be some interaction (indirect?) between the tabset/tab, the controller, and the datepicker. 

-Regards
David

**Comment by mehmetotkun** [comment]
OK. It seems that, ng-model watcher is excequting before scope.currentDate setted due to controller.

if you replace

```
scope.$parent.$watch(attr.ngModel, function (newValue, oldValue) {
    if (newValue && !scope.modelSetted) {
        apply(function () {
            var dt = moment(newValue, scope.format);
            if (options.timepicker) {
                var hr = dt.hour()
                if (hr < options.minHour)
                    dt.hour(options.minHour)
                if (hr > options.maxHour)
                    dt.hour(options.maxHour).minute(0)
            }
            scope.currentDate = dt;
            scope.selectedDay = scope.currentDate.month() + '-' + scope.currentDate.date();
            scope.modelSetted = true;
            fireChange()
            buildNew()
        })
    }
    ngModel.$render();
    apply(function () {
        scope.modelDate = scope.currentDate.clone().toDate();
    })
    if (options.autoHide && !options.timepicker)
        $picker.hide();
})
```

with below code

```
scope.$parent.$watch(attr.ngModel, function (newValue, oldValue) {
    if (newValue) {
        if (!scope.modelSetted) {
            apply(function () {
                var dt = angular.isDate(newValue) ?moment(newValue) : moment(newValue, scope.format);
                if (options.timepicker) {
                    var hr = dt.hour()
                    if (hr < options.minHour)
                        dt.hour(options.minHour)
                    if (hr > options.maxHour)
                        dt.hour(options.maxHour).minute(0)
                }
                scope.currentDate = dt;
                scope.selectedDay = scope.currentDate.month() + '-' + scope.currentDate.date();
                scope.modelSetted = true;
                fireChange()
                buildNew()
            })
        }
        ngModel.$render();
        apply(function () {
            scope.modelDate = scope.currentDate.clone().toDate();
        })
        if (options.autoHide && !options.timepicker)
            $picker.hide();
    }
})
```

your problem will be solved.

**Comment by djmarcus1** [comment]
Hi

The code in my copy of QUI already has the code you are suggesting (see image attached below; it has line number of my version of the code). 

Are you testing with the same version as is your distribution?

When I force a break at the entry to the `$watch` call back, I see that both `newValue` and `oldValue` are `undefined`.

I think the new code should therefore read (note the adding of `!` in front of `newValue` in the `if` expression):

```
if (!newValue && !scope.modelSetted) {
```

Otherwise, the inner code that sets the `currentDate` will not be executed.

I tried this as well and I still get an error (the call to `buildNew()` internally calls `buildFirst(disablenew)` where it sets `$target = $picker.$target;`. Unfortunately, the value of '$picker.$target' is `undefined` which causes an error down the line.

Are you able to reproduce the problem on your system?

-David

This is the code that is in the QUI distribution. As you can see, it is identical to what you are suggesting I make the change to. You should also look at the line numbers to make sure it matches what you have.

![qui-snapshot2](https://cloud.githubusercontent.com/assets/3149616/8635068/7257aa46-27e1-11e5-9219-7ef6e1d71d92.jpg)

**Comment by mehmetotkun** [comment]
OK. Please wait until tomorrow nigth. I will publish new release.

**Comment by djmarcus1** [comment]
Hi

I made some local changes that fix (or probably just hide) the problem.

Notice that I added an explicit check for undefined in the `apply`. When `undefined` I set the value to 'today' (from the moment.js documentation), and set the `scope.selectedDay`. At least the error no longer shows up.

```
ngModel.$render();
apply(function () {
    if (!scope.currentDate) {
        scope.currentDate = moment(new Date(), scope.format);
        scope.selectedDay = scope.currentDate.month() + '-' + scope.currentDate.date();
    }
    scope.modelDate = scope.currentDate.clone().toDate();
})
```

**Comment by djmarcus1** [comment]
By the way, the code in the snippet of code you sent, the `$watch` does not seem to work all the time. 

When the watch is triggered with and new value and old value both `undedfined` the code crashes in an internal call to `buildNew`.

I am seeing an `undefined` error in the call to `buildNew()` [`buildNew()` calls `buildFirst(true)` which gets `$picker.$target` which is `undefined`].

I'm hoping you can fix this as well. I am in a time crunch. I need to make a presentation of the working system by Monday morning and so far I am unable to show a working system using QUI.

-David

**Comment by mehmetotkun** [comment]
Hi David,

The controller inside the tab change all proccess of the picker. For this reason, I changed the running proccess of the component. I sent to you the picker last code via email. You can replace.

Also, If I publish new version, I think there will be no problem on your existing works.

**Comment by djmarcus1** [comment]
The new code you sent me solved the problem.

-Thanks
David
