### ISSUE TITLE
DatePicker: August 2015 is not displaying August 31

### ISSUE THREAD

**Issue by djmarcus1** [quantumui/quantumui#47]
The datepicker is not displaying the entire month when the month requires 6 rows.

Example: Look at August 31, 2015.

This can easily be seen on the QUI demo page for datepicker. See attached screen shot.

-Regards
David

![qui-snapshot3](https://cloud.githubusercontent.com/assets/3149616/8638217/eb128c12-2881-11e5-900e-b64c206db210.jpg)

**Comment by mehmetotkun** [comment]
Ok sorry, There was a caclutaion problem.

Replace 

```
if (wEnd < mEnd)
    wEnd.add(7, 'day')
```

with

```
if (wEnd <= mEnd)
    wEnd.add(7, 'day')
```

**Comment by djmarcus1** [comment]
This fixed the problem

By the way, the Visual Studio javascript syntax checker is flagging all the lines that don’t end with a semicolon when they should.

I guess the browsers’ javascript engines are very forgiving.

My suggestion is when you run across such lines, they should be properly terminated.

Also, for all its worth, Visual Studio is noticing that line endings are mixed. Sometimes they are in Windows format and some are in Unix format. I guess it depends on what editor you use when editing the code.

-Regards & thanks
David
