### ISSUE TITLE
Possible to set switch button by script?

### ISSUE THREAD

**Issue by booms-edv** [quantumui/quantumui#48]
Hello,

in my controller I need to set the checked status to true or false depending which status my database item contains.
Until yet I didnt found a way how to get my needs working.

Please tell me how to set the "checked" state to true or false.

Thanks.

**Comment by mehmetotkun** [comment]
By default `trueValue` and `falseValue` options are true/false. If your model property name **checked** use it like below.

```
<input ng-model="myObject.checked" data-nq-switch-button="" type="checkbox">
```
