### ISSUE TITLE
nqModal: backdrop disappear  when typeClass is used

### ISSUE THREAD

**Issue by pibi** [quantumui/quantumui#49]
Hi,
when you set a typeClass in a modal, its backdrop disappear. Inspecting the element I see that the typeClass value is prefixed on the backdrop element.

example: typeClass value :  llpop,    outer div class: "modal ng-scope pop-master llpop near-top" , backdrop class: "llpop-backdrop in"

**Comment by mehmetotkun** [comment]
Hi,

Beacuse `typeClass` propery change the type of component. alert, popoever, select etc... each component have it's own typeClass. Sometime developer want to create a component, just specify some css. In this case, `typeClass` can be uses.

If you want to just applying custom theme, you can use `theme` option.
