### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by marklagendijk** [quantumui/quantumui#7]
The name `AngularUI` is already used by [another open source project](https://angular-ui.github.io). Because this other open source project is very well known, your usage of the term really looks like you are deliberately trying to confuse people.

Could you stop using the `AngularUI` name?

**Comment by mehmetotkun** [comment]
Thank you for your notice Mark,

I want to explain some point by virtue of your notice;

First; My project name is **QunatumUI** not AngularUI...

Second: There is no project named **AngularUI** as I know. The group you referanced is just a team name not project name.

Third: AngularUI is my company name and I don't want to change it.

And Last: This matter between me and other team.

**Comment by marklagendijk** [comment]
@mehmetotkun did you, or didn't you know about the real AngularUI before you started your 'company'?
AngularUI *is* a project. It describes itself as: 'The companion suite(s) to the AngularJS framework.'. This very big project consists of several sub-projects.

Don't get me wrong, I respect the work you are doing with you QuantumUI project and other UI project. It just annoys me that you seem to deliberately try to lift on the success of the existing, well known project. If you want people to take you seriously, you really should not do things like this.

**Comment by swalters** [comment]
I would also point out that AngularUI was sanctioned by Google Angular team in the early days. While they don't officially support it, they owner of the project did have many conversations with them.  You face some real issues using this name and you will never be able to trademark it in the US.

**Comment by ProLoser** [comment]
Actually, AngularUI is a project: https://github.com/angular-ui/angular-ui-OLDREPO

It is pretty self-evident that you seem to be trying to bank on the notoriety our project and organization worked hard to build. And we were formed way back when angular was v0.9

If you wanted to merge efforts we would be open to that as we're a very open organization where just about every project and team is run independently if you were trying to have the official angular-ui backing.

**Comment by mehmetotkun** [comment]
@marklagendijk I understand your sensitivity. However, there was long time that I get my company name as **AngularUI** form github. 

Also I believe that my project don't need to lift on any other project name, popularity or success. Because, I think it is very strong and successful project. 

Ultimately, there are quite difference between my project and **angular-ui** team projects. I have declared my project as **QuntumUI** on everywhere.

However, I would take into consideration your comments about this issue and reassessing change the company name or not.

@ProLoser I would be pleased to support angular-ui team projects in every stage. Because, as a result we have been tired to wide usage of AngularJS.

**Comment by tkrotoff** [comment]
> there was long time that I get my company name as AngularUI form github

Domain name angularui.net has been created on [July 05, 2014](https://who.is/whois/angularui.net). Your GitHub account (mehmetotkun) has been created on Mar 19, 2014. So **several years** after the creation of [`AngularUI`](https://angular-ui.github.io/).

> My project name is QuantumUI not AngularUI...

Really?

- The website where you present your project:
![](http://s2.postimg.org/fdd1t7pex/Screen_Shot_2015_03_09_at_21_28_58.png)

- An image that you share on Google+:
![](http://s17.postimg.org/urtleevdb/angularui_manset.png)

**Comment by mehmetotkun** [comment]
@tkrotoff thin is my other account @fulladmin. Please check it's creation date too.

Also I don't fall in love with AngularUI name. My project is more than a name.
