### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by bugmenot2** [quantumui/quantumui#92]
Your main site (quantumui.org) with files, examples and docs is down!!

**Comment by mehmetotkun** [comment]
Hosting service provider(Hostmantis) is complately down. I am waiting for solution.

**Comment by bugmenot2** [comment]
I hope you have a backup of all files.
Is absurd that an hosting service is down for more than 72 hours..
Please upload all documentation on github or on another free hosting, waiting to unlock this situation....

**Comment by bugmenot2** [comment]
Site up. Thanks.

**Comment by mehmetotkun** [comment]
me too...
