### ISSUE TITLE
improve docs nqPopover (programmatically)

### ISSUE THREAD

**Issue by bugmenot2** [quantumui/quantumui#93]
Please add more example of how to use your widgets programmatically.
I'm trying to close a popover programmatically (from another function on my scope) but I do not understand how..
Moreover, I do not understand how to use the SCOPE ARGUMENTS mentioned in the docs.. (for ex. in the nqPopover there is $hide() as scope arguments, but where I can access to them?

**Comment by mehmetotkun** [comment]
Scope arguments cen be used inside HTML templates. `ng-click="$hide()`

`$popover` factory cannot be used complately programmatically like `$alert`. Because it needs a HTML element.

http://quantumui.org/appdoc/documents/quantumui/popover/examples

There is an _Using Custom Template_ title in above page. You can see detailed example under this title.

**Comment by bugmenot2** [comment]
1) Scope arguments: this simple example do not work to me

```
<div>
    <button type="button" class="btn btn-default" data-nq-popover="" data-qo-placement="right-bottom"> OPEN   </button>
<div class="popover" data-placement="bottom">
      <h3 class="popover-title">MyPop</h3>
      <div class="popover-content">
        <div>
          <button type="button" class="btn btn-sm btn-success" ng-click="$hide()">CloseME</button>
        </div>
      </div>
    </div>
  </div>
```

2) I see customTemplate and programmatically usage example, but there is nothing really helpful form me. Can open/close a specific popover from my function (in my controller, out of template) I think is a common use-case...

**Comment by mehmetotkun** [comment]
Here is the solution for you. You want to use popover like a modal.
You don't need to use `button` element for creating button. If you want to access scope arguments, you must use custom template or all of your content must be inside the directive.

```
<div data-nq-popover="" class="btn btn-default">
          OPEN
          <div class="popover">
            <h3 class="popover-title">Popover Scope Arguments</h3>
            <div class="popover-content">
              <p>Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>
              <div>
                <button type="button" class="btn btn-sm btn-success" ng-click="$hide()">Close Me</button>
              </div>
            </div>
          </div>
        </div>
```

**Comment by bugmenot2** [comment]
Ok, thank you (yes, I'm trying it with `button` element)
I think that can be useful an example like this in the docs.
Moreover, someone can use `ng-init="myFun($hide)"` to save the hide function in the `scope`and use it when him prefers...

**Comment by mehmetotkun** [comment]
The document is not up do date yet. But there is `popoverModel` option in new version.

Namely if you use `data-nq-popover="" popover-model="myPopoverModel"` you can access all functions and methods of '$popover'.
Eg. in your controller.

```
$scope.myPopoverModel = {};

function closePopover(){
  //access popover scope
   var popScope = $scope.myPopoverModel.$scope;
   //do what you want with scope
   //the methods of scope like $hide, $show has no '$' char in popover controller. This an architectural rule of QUI
    $scope.myPopoverModel.hide();
}
```
